Job mysql

diff --git a/deploy/mysql.yaml b/deploy/mysql.yaml
--- a/deploy/mysql.yaml
+++ b/deploy/mysql.yaml
@@ -76,3 +76,50 @@ spec:
 
 ---
 
+# Job
+
+apiVersion: batch/v1
+kind: Job
+metadata:
+  name: mysql-setup
+spec:
+  template:
+    spec:
+      containers:
+        - name: mysql-client
+          image: mysql:8.4
+          command: ["/bin/sh", "-c"]
+          args:
+            - |
+              # Install wget
+              microdnf update && microdnf install -y wget && microdnf clean all
+              
+              # Download the SQL file
+              wget -O data.sql "https://drive.google.com/uc?export=download&id=1AC2uvs6f2t4qrhXpz5XowSxoVXR3TfvG"
+              
+              
+              # Check if the file was downloaded successfully
+              if [ ! -f data.sql ]; then
+                echo "Failed to download data.sql"
+                exit 1
+              fi
+              
+              # Execute SQL commands
+              
+              mysql -h mysql -u root -proot <<EOF
+              CREATE DATABASE IF NOT EXISTS google;
+              ALTER USER 'metabase'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
+              GRANT ALL PRIVILEGES ON metabase.* TO 'metabase'@'%';
+              GRANT ALL PRIVILEGES ON google.* TO 'metabase'@'%';
+              FLUSH PRIVILEGES;
+              EOF
+              
+              # Import the SQL file
+              mysql -h mysql -u root -proot google < data.sql
+          env:
+            - name: MYSQL_ROOT_PASSWORD
+              valueFrom:
+                secretKeyRef:
+                  name: mysql-secret
+                  key: MYSQL_ROOT_PASSWORD
+      restartPolicy: OnFailure
