save

diff --git a/deploy/mysql.yaml b/deploy/mysql.yaml
--- a/deploy/mysql.yaml
+++ b/deploy/mysql.yaml
@@ -64,13 +64,12 @@ spec:
 apiVersion: v1
 kind: Service
 metadata:
-  name: kb-metabase
+  name: kb-mysql
 spec:
   selector:
-    app: metabase
+    app: mysql
   ports:
-    - port: 80
-      targetPort: 3000
+    - port: 3306
 ---
 
 # Job
@@ -78,199 +77,45 @@ spec:
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: metabase-setup
+  name: mysql-setup
 spec:
   template:
     spec:
-      # initContainers:
-      # - name: wait-for-metabase-setup
-      #   image: busybox
-      #   command: ['sh', '-c', 'until nslookup kb-metabase; do echo waiting for metabase; sleep 2; done']
       containers:
-        - name: metabase-setup
-          image: alpine
+        - name: mysql-client
+          image: mysql:8.4
           command: ["/bin/sh", "-c"]
           args:
             - |
-              # Install curl
-              apk add --no-cache curl
+              # Install wget
+              microdnf update && microdnf install -y wget && microdnf clean all
+              
+              # Download the SQL file
+              wget -O data.sql "https://drive.google.com/uc?export=download&id=1AC2uvs6f2t4qrhXpz5XowSxoVXR3TfvG"
               
               
-              # Instalar jq
-              apk add --no-cache jq
-              
-              # Wait for Metabase to be ready
-              until curl -s http://kb-metabase/api/health | grep -q "ok"; do
-                echo "Waiting for Metabase to start..."
-                sleep 10
-              done
-              
-              # Get session token if user exists
-              SESSION_TOKEN=$(curl -X POST http://kb-metabase/api/session \
-                -H "Content-Type: application/json" \
-                -d '{
-                  "username": "'$ADMIN_EMAIL'",
-                  "password": "'$ADMIN_PASSWORD'"
-                }' | jq -r '.id')
-              
-              if [ "$SESSION_TOKEN" == "null" ] || [ -z "$SESSION_TOKEN" ]; then
-                # Get setup token
-                SETUP_TOKEN=$(curl -s http://kb-metabase/api/session/properties | jq -r '.["setup-token"]')
-              
-                # Set up admin account
-                curl -X POST http://kb-metabase/api/setup \
-                  -H "Content-Type: application/json" \
-                  -d '{
-                    "token": "'$SETUP_TOKEN'",
-                    "user": {
-                      "first_name": "augusto",
-                      "last_name": "kark",
-                      "email": "'$ADMIN_EMAIL'",
-                      "password": "'$ADMIN_PASSWORD'",
-                      "password_confirm": "'$ADMIN_PASSWORD'"
-                    },
-                    "prefs": {
-                      "site_name": "UM",
-                      "site_locale": "en"
-                    }
-                  }'
-              
-                # Get session token after setup
-                SESSION_TOKEN=$(curl -X POST http://kb-metabase/api/session \
-                  -H "Content-Type: application/json" \
-                  -d '{
-                    "username": "'$ADMIN_EMAIL'",
-                    "password": "'$ADMIN_PASSWORD'"
-                  }' | jq -r '.id')
+              # Check if the file was downloaded successfully
+              if [ ! -f data.sql ]; then
+                echo "Failed to download data.sql"
+                exit 1
               fi
               
-              if [ -n "$SESSION_TOKEN" ] && [ "$SESSION_TOKEN" != "null" ]; then
-                # Check if the dashboard already exists
-                DASHBOARD_EXISTS=$(curl -X GET http://kb-metabase/api/dashboard \
-                  -H "X-Metabase-Session: $SESSION_TOKEN" | jq '.[] | select(.name == "Mobility Dashboard")')
+              # Execute SQL commands
               
-                if [ -z "$DASHBOARD_EXISTS" ]; then
-                  # Add database connection
-                  DB_ID=$(curl -X POST http://kb-metabase/api/database \
-                    -H "Content-Type: application/json" \
-                    -H "X-Metabase-Session: $SESSION_TOKEN" \
-                    -d '{
-                      "engine": "mysql",
-                      "name": "mobility",
-                      "details": {
-                        "host": "kb-mysql",
-                        "port": 3306,
-                        "dbname": "google",
-                        "user": "'$DB_USER'",
-                        "password": "'$DB_PASSWORD'"
-                      },
-                      "is_full_sync": true,
-                      "auto_run_queries": true
-                    }' | jq -r '.id')
+              mysql -h kb-mysql -u root -p$MYSQL_ROOT_PASSWORD <<EOF
+              CREATE DATABASE IF NOT EXISTS google;
+              ALTER USER 'metabase'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
+              GRANT ALL PRIVILEGES ON metabase.* TO 'metabase'@'%';
+              GRANT ALL PRIVILEGES ON google.* TO 'metabase'@'%';
+              FLUSH PRIVILEGES;
+              EOF
               
-                  # Create dashboard
-                  DASHBOARD_ID=$(curl -X POST http://kb-metabase/api/dashboard \
-                    -H "Content-Type: application/json" \
-                    -H "X-Metabase-Session: $SESSION_TOKEN" \
-                    -d '{
-                      "name": "Mobility Dashboard",
-                      "description": "Mobility data for Mendoza Province, Capital Department"
-                    }' | jq -r '.id')
-              
-                  # Creating question...
-                  QUESTION_ID=$(curl -X POST http://kb-metabase/api/card \
-                    -H "Content-Type: application/json" \
-                    -H "X-Metabase-Session: $SESSION_TOKEN" \
-                    -d '{
-                      "name": "average mendoza",
-                      "type": "question",
-                      "dataset_query": {
-                        "database": '"$DB_ID"',
-                        "type": "query",
-                        "query": {
-                          "source-table": 9,
-                          "aggregation": [
-                            ["avg", ["field", 83, {"base-type": "type/Integer"}]],
-                            ["avg", ["field", 81, {"base-type": "type/Integer"}]],
-                            ["avg", ["field", 72, {"base-type": "type/Integer"}]],
-                            ["avg", ["field", 80, {"base-type": "type/Integer"}]],
-                            ["avg", ["field", 78, {"base-type": "type/Integer"}]],
-                            ["avg", ["field", 86, {"base-type": "type/Integer"}]]
-                          ],
-                          "breakout": [["field", 73, {"base-type": "type/DateTime", "temporal-unit": "day"}]],
-                          "filter": [
-                            "and",
-                            ["=", ["field", 85, {"base-type": "type/Text"}], "Mendoza Province"],
-                            ["=", ["field", 75, {"base-type": "type/Text"}], "Capital Department"],
-                            ["between", ["field", 73, {"base-type": "type/DateTime"}], "2020-01-01", "2020-12-31"]
-                          ]
-                        }
-                      },
-                      "display": "area",
-                      "description": null,
-                      "visualization_settings": {
-                        "stackable.stack_type": null,
-                        "graph.dimensions": ["date"],
-                        "graph.metrics": ["avg", "avg_2", "avg_3", "avg_4", "avg_5", "avg_6"]
-                      },
-                      "collection_id": null,
-                      "collection_position": null,
-                      "result_metadata": [
-                        {"description": null, "semantic_type": null, "coercion_strategy": null, "unit": "day", "name": "date", "settings": null, "fk_target_field_id": null, "field_ref": ["field", 73, {"base-type": "type/DateTime", "temporal-unit": "day"}], "effective_type": "type/Date", "id": 73, "visibility_type": "normal", "display_name": "Date", "fingerprint": {"global": {"distinct-count": 321, "nil%": 0}, "type": {"type/DateTime": {"earliest": "2020-02-15T00:00:00Z", "latest": "2020-12-31T00:00:00Z"}}}, "base_type": "type/Date"},
-                        {"display_name": "Average of Retail And Recreation Percent Change From Baseline", "semantic_type": null, "settings": null, "field_ref": ["aggregation", 0], "base_type": "type/Decimal", "effective_type": "type/Decimal", "name": "avg", "fingerprint": {"global": {"distinct-count": 95, "nil%": 0}, "type": {"type/Number": {"min": -96, "q1": -69.0857716560905, "q3": -42.84139629549865, "max": 41, "sd": 27.658547670628238, "avg": -52.29283489096573}}}},
-                        {"display_name": "Average of Grocery And Pharmacy Percent Change From Baseline", "semantic_type": null, "settings": null, "field_ref": ["aggregation", 1], "base_type": "type/Decimal", "effective_type": "type/Decimal", "name": "avg_2", "fingerprint": {"global": {"distinct-count": 101, "nil%": 0}, "type": {"type/Number": {"min": -91, "q1": -30.805717884568125, "q3": 0.5971624461628744, "max": 83, "sd": 26.054557250362603, "avg": -16.31152647975078}}}},
-                        {"display_name": "Average of Parks Percent Change From Baseline", "semantic_type": null, "settings": null, "field_ref": ["aggregation", 2], "base_type": "type/Decimal", "effective_type": "type/Decimal", "name": "avg_3", "fingerprint": {"global": {"distinct-count": 94, "nil%": 0}, "type": {"type/Number": {"min": -99, "q1": -90.42656981021216, "q3": -50.86001194493218, "max": 59, "sd": 32.48307885753726, "avg": -60.49844236760124}}}},
-                        {"display_name": "Average of Transit Stations Percent Change From Baseline", "semantic_type": null, "settings": null, "field_ref": ["aggregation", 3], "base_type": "type/Decimal", "effective_type": "type/Decimal", "name": "avg_4", "fingerprint": {"global": {"distinct-count": 86, "nil%": 0}, "type": {"type/Number": {"min": -90, "q1": -56.375, "q3": -28.412408759124087, "max": 26, "sd": 21.74401795040259, "avg": -39.48230629282969}}}},
-                        {"display_name": "Average of Workplaces Percent Change From Baseline", "semantic_type": null, "settings": null, "field_ref": ["aggregation", 4], "base_type": "type/Decimal", "effective_type": "type/Decimal", "name": "avg_5", "fingerprint": {"global": {"distinct-count": 100, "nil%": 0}, "type": {"type/Number": {"min": -68, "q1": -52.38269984732978, "q3": -29.372754491017964, "max": -5, "sd": 13.82253782282153, "avg": -37.69674722746238}}}},
-                        {"display_name": "Average of Residential Percent Change From Baseline", "semantic_type": null, "settings": null, "field_ref": ["aggregation", 5], "base_type": "type/Decimal", "effective_type": "type/Decimal", "name": "avg_6", "fingerprint": {"global": {"distinct-count": 72, "nil%": 0}, "type": {"type/Number": {"min": -10, "q1": 4.100000000000003, "q3": 16.89999999999999, "max": 47, "sd": 11.929313682719714, "avg": 11.745752608047334}}}}
-                      ],
-                      "archived": false,
-                      "enable_embedding": false,
-                      "embedding_params": null,
-                      "cache_ttl": null
-                    }' | jq -r '.id')
-              
-                  # Add question to dashboard
-                  curl -X POST http://kb-metabase/api/dashboard/$DASHBOARD_ID/cards \
-                    -H "Content-Type: application/json" \
-                    -H "X-Metabase-Session: $SESSION_TOKEN" \
-                    -d '{
-                      "cardId": '"$QUESTION_ID"',
-                      "row": 0,
-                      "col": 0,
-                      "sizeX": 4,
-                      "sizeY": 4
-                    }'
-                else
-                  echo "Dashboard 'Mobility Dashboard' already exists. Skipping creation."
-                fi
-              else
-                echo "Failed to create or retrieve Metabase session token."
-              fi
+              # Import the SQL file
+              mysql -h kb-mysql -u root -p$MYSQL_ROOT_PASSWORD google < data.sql
           env:
-            - name: ADMIN_EMAIL
-              valueFrom:
-                secretKeyRef:
-                  name: metabase-secret
-                  key: ADMIN_EMAIL
-            - name: ADMIN_PASSWORD
-              valueFrom:
-                secretKeyRef:
-                  name: metabase-secret
-                  key: ADMIN_PASSWORD
-            - name: DB_NAME
+            - name: MYSQL_ROOT_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: mysql-secret
-                  key: MYSQL_DATABASE
-            - name: DB_USER
-              valueFrom:
-                secretKeyRef:
-                  name: mysql-secret
-                  key: MYSQL_USER
-            - name: DB_PASSWORD
-              valueFrom:
-                secretKeyRef:
-                  name: mysql-secret
-                  key: MYSQL_PASSWORD
+                  key: MYSQL_ROOT_PASSWORD
       restartPolicy: OnFailure
